# ---- Etapa 1: build ----
FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build


# ---- Etapa 2: tests ----
FROM build AS test

ENTRYPOINT ["npm", "run", "test:ci"]


# ---- Etapa 3: nginx ----
FROM nginx:alpine

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]